### ISSUE TITLE
Import issues from original version to forked one

### ISSUE THREAD

**Issue by rugk** [rugk/threema-msgapi-sdk-php#5]
It would be good to import the (open) issues from the [original SDK](https://github.com/threema-ch/threema-msgapi-sdk-php) here.

It would be nice if @threema could help a bit e.g. by sending a list of all issues which were open until the repo was closed or by temporarily reopening the issue tracker so so it can be copied.

Otherwise I just have to remember.
So this is the current list of open issues I remember:
- [x] use git submodule, by rugk; fixed in https://github.com/rugk/threema-msgapi-sdk-php/pull/19
- [x] Key Pinning, by rugk; see https://github.com/rugk/threema-msgapi-sdk-php/issues/21
- [x] Contributing guide, by rugk; fixed in https://github.com/rugk/threema-msgapi-sdk-php/commit/f59ea71c329674851b9035bc9dd204cce1f0417a
- [x] add Continuous integration, by rugk; see https://github.com/rugk/threema-msgapi-sdk-php/issues/22

**Comment by rugk** [comment]
As I finally got access to the issues of the old repo here the list of missing issues:
- [x] "Add Contributing.md", by rugk; now tracked in https://github.com/rugk/threema-msgapi-sdk-php/issues/16

As I have now imported all issues I close this issue.
